[package]
name = "cc"
version = "0.1.0"
authors = ["shell <shell@thisworld.club>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
